### PR TITLE
added missing backslash to $k in response_parser_template.php

### PR DESCRIPTION
**Pull request by litlfred**

### CODE REVIEW

**Comment by dcarbone** [comment]
Oops :)

**Comment by litlfred** [comment]
Just noticed there is a missing case near there as well.  Will do another PR in a moment

**Comment by dcarbone** [comment]
Ugh, never code while tired.  Thanks for this.

**Comment by litlfred** [comment]
looks like you already added the case stmts so won't do a PR

**Comment by dcarbone** [comment]
Yeah I figured it'd just be easier.  Thanks for pointing it out though!  Please let me know if you see any other issues, I hope to have time to get back to work on this lib this weekend.

**Pull request merged**
